### ISSUE TITLE
Unable to access camera (secure context error)

### ISSUE THREAD

**Issue by nao-hoshino** [Filiprogrammer/SimpleJadePinServer#11]
Hello,

I just tried testing out the pin server in anticipation of receiving my Jade next week.

However, when I try to initiate a QR scan from my mobile device (by clicking 'Request Camera Permissions'), I get the following error:

**_"Camera access is only supported in secure context like https or localhost"_**
![camera](https://github.com/user-attachments/assets/9dde7b77-310b-49a5-ab29-8fac79e98d9e)

I'm currently running the pin server on my desktop PC via docker compose - is there any way around this restriction?

**Comment by Filiprogrammer** [comment]
You can generate a self signed certificate as described in the [README](https://github.com/Filiprogrammer/SimpleJadePinServer?tab=readme-ov-file#optional-get-an-ssltls-certificate) and remove the `--no-tls` option from the `docker-compose.yml` file:
```diff
@@ -5,4 +5,4 @@
       - "18080:4443"
     volumes:
       - ./key_data:/app/key_data
-    command: ["--no-tls"]
+    command: []
```

An alternative way is to use a reverse proxy like nginx or Caddy as mentioned by the [README](https://github.com/Filiprogrammer/SimpleJadePinServer?tab=readme-ov-file#alternative-use-a-reverse-proxy)

**Comment by nao-hoshino** [comment]
That did the trick, thank you!
