### ISSUE TITLE
"Network or server error" on Step 2/4 start_handshake

### ISSUE THREAD

**Issue by petre-c** [Filiprogrammer/SimpleJadePinServer#4]
Hey @Filiprogrammer , I saw you implemented setting a blind oracle with QR, well done and thank you!

I gave it a try - Oracle QR gets scanned successfully.
After that, Jade produces a 'Network or server error' on **Step 2/4 start_handshake**:
![image](https://github.com/user-attachments/assets/966af5bd-64a1-48a9-9395-32b33ac054c4)

I tried it on a debian distro and [with docker](https://github.com/Filiprogrammer/SimpleJadePinServer/pull/5).

My Jade is on firmware version 1.0.31.

Log from the terminal:
![image](https://github.com/user-attachments/assets/d0687ac0-2404-48e0-9eab-8117376ac0c2)

**Comment by Filiprogrammer** [comment]
This error message usually appears when the static public key of the pin server does not match the oracle public key configured on the Jade. Are you certain that you have not regenerated the `private.key` and `public.key` after configuring the blind oracle on the Jade?

**Comment by petre-c** [comment]
> This error message usually appears when the static public key of the pin server does not match the oracle public key configured on the Jade. Are you certain that you have not regenerated the `private.key` and `public.key` after configuring the blind oracle on the Jade?

Yes, I am certain that I have not regenerated the `private.key` and 'public.key`
[server_keys.zip](https://github.com/user-attachments/files/17657303/server_keys.zip)

I have attached them

**Comment by Filiprogrammer** [comment]
Which firmware version is your Jade on? Mine is on 1.0.24. I have tried with your keys and I cannot reproduce your problem.

**Comment by Filiprogrammer** [comment]
Ok I see what's going on. In firmware version 1.0.28 the pinserver oracle protocol was changed to have only 2 steps.

> Changed pinserver oracle protocol to only require a single roundtrip, exchanging a single base64-encoded string

 My implementation was made for the old 4 step protocol.

**Comment by petre-c** [comment]
> Ok I see what's going on. In firmware version 1.0.28 the pinserver oracle protocol was changed to have only 2 steps.
> 
> > Changed pinserver oracle protocol to only require a single roundtrip, exchanging a single base64-encoded string
> 
>  My implementation was made for the old 4 step protocol.

And you will update your code to reflect the change, is that correct reasoning on my part?

**Comment by Filiprogrammer** [comment]
From my testing I can confirm that 1.0.27 is the last version that works with SimpleJadePinServer.

> And you will update your code to reflect the change, is that correct reasoning on my part?

I will look into it. It may take some time though, as I have a few other tasks on my plate at the moment.

**Comment by petre-c** [comment]
Okay, I will wait patiently 🙂

**Comment by petre-c** [comment]
@Filiprogrammer , have you had a chance to look into this?
